mysite/files/urls.py
from django.views.generic.base import TemplateView
from files.views import FilePolicyAPI, FileUploadCompleteHandler, VideoFileUploadView
from django.urls import path


urlpatterns = [

    path('upload/', TemplateView.as_view(template_name='files/upload.html'), name='upload-home'),
    path('api/files/policy/', FilePolicyAPI.as_view(), name='upload-policy'),
    path('api/files/complete/', FileUploadCompleteHandler.as_view(), name='upload-complete'),

    # path('video-upload/store/<slug:slug>/', VideoFileUploadView.as_view(), name='merchant_video_upload'),







]

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.text import slugify

class Topic(models.Model):
    title       = models.CharField(max_length=25, verbose_name='Title')
    slug        = models.SlugField(max_length=100)
    body        = models.TextField(blank=True, null=True)
    created_at  = models.DateTimeField(default=timezone.now, verbose_name="Created at")
    updated_at  = models.DateTimeField(default=timezone.now, verbose_name="Updated at")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('topics_detail', kwargs={'slug': self.slug})

class Question(models.Model):

    STATUS_CHOICES = {
        ('draft', 'Draft'),
        ('published', 'Published'),
    }

    title       = models.CharField(max_length=100)
    topic       = models.ForeignKey(Topic, on_delete=models.CASCADE, blank=True, null=True)
    slug        = models.SlugField(max_length=100)
    # author      = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='blog_post')
    body        = models.TextField()
    status      = models.CharField(max_length=20, choices=STATUS_CHOICES, default='draft')
    created_at  = models.DateTimeField(default=timezone.now, verbose_name="Created at")
    updated_at  = models.DateTimeField(default=timezone.now, verbose_name="Updated at")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('questions_detail', kwargs={'slug': self.slug})

@receiver(pre_save, sender=Question)
def pre_save(sender, **kwargs):
    slug = slugify(kwargs['instance'].title)
    kwargs['instance'].slug = slug



class Contact(models.Model):
    REASON_CHOICES = (
        ("QT", "I have a Question"),
        ("DS", "Dissatisfied with a Coupon"),
        ("BM", "I Would Like to post my own Coupons"),
        )

    reason = models.CharField(choices=REASON_CHOICES, default='QT', max_length=100)
    name = models.CharField(max_length=200)
    email = models.EmailField()
    phone = PhoneNumberField(null=True, blank=True)   #USE THIS https://github.com/stefanfoulis/django-phonenumber-field\
    description = models.TextField()

mysite/search/models.py
from django.db import models

# Create your models here.

mysite/search/forms.py
from haystack.forms import FacetedSearchForm
from portal.models import Category, Subcategory, Offer


class FacetedOfferSearchForm(FacetedSearchForm):

    def __init__(self, *args, **kwargs):
        data = dict(kwargs.get("data", []))
        self.category = data.get('category', [])
        self.subcategory = data.get('subcategory', [])
        self.city = data.get('city', [])
        super(FacetedOfferSearchForm, self).__init__(*args, **kwargs)

    def search(self):
        sqs = super(FacetedOfferSearchForm, self).search()
        if self.category:
            query = None
            for category in self.category:
                if query:
                    query += u' OR '
                else:
                    query = u''
                query += u'"%s"' % sqs.query.clean(category)
            sqs = sqs.narrow(u'category_exact:%s' % query)

        if self.subcategory:
            query = None
            for subcategory in self.subcategory:
                if query:
                    query += u' OR '
                else:
                    query = u''
                query += u'"%s"' % sqs.query.clean(subcategory)
            sqs = sqs.narrow(u'subcategory_exact:%s' % query)

        if self.city:
            query = None
            for city in self.city:
                if query:
                    query += u' OR '
                else:
                    query = u''
                query += u'"%s"' % sqs.query.clean(city)
            sqs = sqs.narrow(u'city_exact:%s' % query)

        return sqs
  #if self.brands:
  #query = None
  #for brand in self.brands:
  #if query:
  #query += u' OR '
  #else:
  #query = u''
  #query += u'"%s"' % sqs.query.clean(brand)
  #sqs = sqs.narrow(u'brand_exact:%s' % query)
  #return sqs

mysite/search/views.py
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.http import JsonResponse
from haystack.generic_views import FacetedSearchView as BaseFacetedSearchView
from haystack.query import SearchQuerySet

from portal.models import Offer, Category, Store
from .forms import FacetedOfferSearchForm

#Location
from location.functions import get_or_set_location
from django.contrib.gis.db import models
from django.contrib.gis.geos import Point
from django.contrib.gis.db.models.functions import Distance

#class HomeView(TemplateView):
#  template_name = "home.html"

#class ProductView(DetailView):
#  template_name = "product.html"
#  model = Product

def autocomplete(request):
    sqs = SearchQuerySet().autocomplete(content_auto=request.GET.get('query',''))[:5]
    s = []
    for result in sqs:
        d = {"value": result.business_name, "data": result.slug}
        s.append(d)
    output = {'suggestions': s}
    return JsonResponse(output)


class FacetedSearchView(BaseFacetedSearchView):
    form_class = FacetedOfferSearchForm
    facet_fields = ['category', 'subcategory', 'city']
    template_name = 'search/search_result.html'
    context_object_name = 'object_list'
    #
    #
    # def get_queryset(self):
    #     objects = super(FacetedSearchView, self).get_results(self)
    #     city_state = get_or_set_location(self.request)
    #     user_location = city_state["user_location"]
    #     return self.objects.annotate(distance = Distance("location", user_location)).order_by("distance").filter(status=2)[0:8]


    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        city_state = get_or_set_location(self.request)
        user_location = city_state["user_location"]
        try:
            context['advert_list'] = Store.objects.annotate(distance = Distance("location", user_location)).order_by("distance").filter(status=2)[0:4]
        except:
            context['advert_list'] = Store.objects.filter(city='Novi', state='Michigan', status=2)[0:8]
        return context

mysite/templates/search/search.html
{% extends "base.html" %}


{% block content %}

  <main class="">
    <section class="section-md">
      <div class="container">
          {% block search_form  %}
              {% include "search/search_form.html" %}
          {% endblock search_form %}


        <div class="row">
          <div class="col-lg-12">
            <div class="row">
              {% for object in items %}
              <div class="col-lg-4 text-center">
                  <a href="{{ object.get_consumer_absolute_url }}">
                  <img class="card-img-top p-4" style="width: 100%;" src="/media/{{ object.image }}" alt="User Uploaded images">
                  <div class="text-center text-uppercase mt-4">
                    <h3 class="fs-14">{{ object.business_name }}</h3>
                    <span class="text-muted fs-14 ">${{ object.description }}</span>
                  </div>
              </a>
              </div>

              {% empty %}
              <div class="col-lg-12 text-center">
                  <div></div>
                  <h3 class="fs-14">Sorry, we were not able to find anything.</h3>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>

    </section>
  </main>

{% endblock content %}

mysite/templates/search/search0.html
{% extends "base-alt.html" %}


{% block content %}

  <main class="">
    <section class="section-md">
      <div class="container">
          {% block search_form  %}
              {% include "search/search_form.html" %}
          {% blockend search_form %}


        <div class="row">
          <div class="col-lg-12">
            <div class="row">
              {% for object in items %}
              <div class="col-lg-4 text-center">
                  <a href="{{ object.get_absolute_url }}">
                  <img class="card-img-top p-4" style="width: 100%;" src="/media/{{ object.image }}" alt="User Uploaded images">
                  <div class="text-center text-uppercase mt-4">
                    <h3 class="fs-14">{{ object.title }}</h3>
                    <span class="text-muted fs-14 ">${{ object.price }}</span>
                  </div>
              </a>
              </div>

              {% empty %}
              <div class="col-lg-12 text-center">
                  <div></div>
                  <h3 class="fs-14">Sorry, we were not able to find anything.</h3>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>

    </section>
  </main>

{% endblock content %}

mysite/templates/search/search_form.html
{% block search_form  %}
    <form class="search-form-container" action="/find/" method="get" >
        <div class="form-group">
            <div class="icon-addon addon-lg">
                <input type="text" placeholder="what are you looking for ?" class="form-control" name="q" id="q" autocomplete="off">
                <div id="selction-ajax"></div>
            </div>
        </div>
    </form>

{% endblock search_form %}

mysite/templates/search/search_form_insert.html
{% block search_form  %}
    <div class="section-search unhide">
        <div class="search-form-background">
            <form class="search-form-container-navbar" action="/find/" method="get" >
                <div class="" style="width: 100%;">
                    <div class="icon-addon addon-lg">
                        <input type="text" placeholder="Search for Services" name="q" id="q" autocomplete="off">
                        <div id="selction-ajax"></div>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock search_form %}

mysite/templates/search/search_result.html
{% extends "base.html" %}
{% load location_extra %}

{% block title %}
    "{{ query }}" | {{ block.super }}
{% endblock %}

{% block content %}

<section class="section pb-0">
    <div class="container">
        <div class="mb-5">
            <h2>Search Results</h2>
            <span class="fs-14 text-muted">{{ page_obj.paginator.count }} {% if page_obj.paginator.count > 1 %}stores {% else %} store {% endif %} found for: <span class="fw-7">{{query}}</span></span>
        </div>
        <div class="row">
            <!-- ********************************************** -->
            <!--                 Side Filter                    -->
            <!-- ********************************************** -->
            {% if  page_obj.object_list %}
            <div class="col-lg-2 mb-4">
                <div class="accordion" id="myAccordion">
                    <div id="headingThree">
                        <button type="button" class="text-left btn btn-primary-alt px-2 py-2 mb-4 collapsed" data-toggle="collapse" data-target="#collapseThree">Filter Results<i class="fa fa-filter ml-2" aria-hidden="true"></i></button>
                    </div>

                </div>
                <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#myAccordion">
                	<div class="hide">
                        <h4 class="fs-16 fw-6">Filter Choices</h4>
                        <br>
                    </div>

                    <!-- *********************** CATEGORY FILTER *********************** -->
                      <dl>
                        {% if facets.fields.category %}
                            <dt class="fs-14">Category</dt>
                            <hr class="my-1">
                            {% for category in facets.fields.category|slice:":5" %}
                                {% if category.1 != 0 %}
                                    <dd>
                                    <input class="facet " id="{{category.0|cut:" "}}" type="checkbox" name="category" value="{{ category.0 }}"
                                    data-toggle="toggle" /> <span class="fs-14">{{ category.0|title }} ({{ category.1 }})</span>
                                </dd>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                      </dl>

                      <!-- *********************** SUBCATEGORY FILTER *********************** -->

                      <dl class="mt-4">
                        {% if facets.fields.subcategory %}
                            <dt class="fs-14">SubCategory</dt>
                            <hr class="my-1">
                            {% for subcategory in facets.fields.subcategory|slice:":5" %}
                                {% if subcategory.1 != 0 %}
                                    <dd>
                                    <input class="facet " id="{{subcategory.0|cut:" "}}" type="checkbox" name="subcategory" value="{{ subcategory.0 }}"
                                    data-toggle="toggle" /> <span class="fs-14">{{ subcategory.0|title }} ({{ subcategory.1 }})</span>
                                </dd>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                      </dl>

                      <dl class="mt-4">
                        {% if facets.fields.city %}
                            <dt class="fs-14">City</dt>
                            <hr class="my-1">
                            {% for city in facets.fields.city|slice:":5" %}
                                {% if city.1 != 0 %}
                                    <dd>
                                    <input class="facet " id="{{city.0|cut:" "}}" type="checkbox" name="city" value="{{ city.0 }}"
                                    data-toggle="toggle" /> <span class="fs-14">{{ city.0|title }} ({{ city.1 }})</span>
                                </dd>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                      </dl>

                      <div>
                          <input class="btn btn-primary-alt btn-block fs-12 px-3 py-2 pull-right" type="submit" value="Apply filter" onclick="return onFacetChangeApplied();" />
                      </div>
                </div>
            </div>
            {% endif %}
              <!-- ********************************************** -->
              <!--                   Products                     -->
              <!-- ********************************************** -->
            <div class="col-lg-10">
                <div class="row">
                    {{ page_obj.objectlist }}
                    {% if  page_obj.object_list %}
                        {% for result in page_obj.object_list %}
                            <div class="col-lg-4 col-md-6 col-sm-6 text-center border-radius-300 mb-4 px-m-na-3">
                                <div class="card">
                                    <a class="" href="{{ result.object.get_consumer_absolute_url }}">
                                        <img class="img-fluid border-radius-top-100" style="max-height: 200px;" src="{{ AwsBucketMediaURL }}{{ result.object.logo }}" alt="User Uploaded images">
                                    </a>
                                    <div class="card-body py-1 px-3">
                                        <div class=" text-left mt-2">
                                            <a href="{{ result.object.get_consumer_absolute_url }}" class="fw-6 text-primary fs-18 mb-1">{{ result.object.business_name }}</a>
                                            <br>
                                                {% for i in result.object.rating_average_round %}
                                                <span class="fa fa-star star-yellow fs-16"></span>

                                                {% endfor %}
                                                {% for i in result.object.rating_average_round_inverted %}
                                                <span class="fa fa-star-o star-yellow fs-16"></span>
                                                {% endfor %}
                                            <br>
                                            <!-- <span class="fs-12 text-gray-700">{{ result.object.category.get_name_display }} <span class="text-purple-500 px-1">&#8226;</span> {{ result.object.subcategory.name }}</span> -->
                                                {% for result.object in result.object.rating_average.ratingsystem %}
                                                    testimonial
                                                {% endfor %}
                                            <p class="fw-4 text-gray-800 fs-16 fw-4 pt-2 mb-2">
                                                {{ result.object.slogan|truncatewords:8 }}
                                            </p>
                                            <!-- url 'portal:merchant_detail' object.state object.city object.offer.first.merchant.category object.offer.first.merchant.subcategory object.offer.first.merchant.business_name object.offer.first.merchant.ref_code -->
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    <div class="col-lg-12 pt-5 text-muted fs-14">
                        <div class="row">
                            <div class="col-md-12 pull-right">
                                <p class="pull-right fs-14 text-muted">
                                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                                </p>
                            </div>
                        </div>
                            <div class="px-4">
                                {% if is_paginated %}
                                <div class="col-lg-12 py-3 text-center">
                                    <nav aria-label="Page navigation example">
                                        <ul class="pagination pull-right">
                                            {% if page_obj.has_previous %}
                                                <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                                            {% endif %}
                                            {% for num in page_obj.paginator.page_range %}
                                                    {% if page_obj.number == num %}
                                                    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                                                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                                                    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                                                    {% endif %}
                                            {% endfor %}
                                            {% if page_obj.has_next %}
                                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
                                            {% endif %}
                                        </ul>
                                    </nav>
                            </div>
                            {% endif %}
                        </div>
                        {% endif %}
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="py-5"></div>
    <div class="bg-gray-80 p-3 border">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 pb-1 text-left">
                    <h3 class="header fs-16 py-3">Customers who viewed this service also viewed</h3>
                </div>
              {% for object in advert_list %}
                  <div class="col-lg-3 col-md-6 col-sm-6 text-center border-radius-300 mb-4 px-m-na-3">
                      <div class="card">
                          <a class="" href="{{ object.get_consumer_absolute_url }}">
                              <img class="img-fluid border-radius-top-100" style="max-height: 200px;" src="{{ AwsBucketMediaURL }}{{ object.logo }}" alt="User Uploaded images">
                          </a>
                          <div class="card-body py-1 px-3">
                              <div class=" text-left mt-2">
                                  <a href="{{ object.get_consumer_absolute_url }}" class="fw-6 text-primary fs-18 mb-1">{{ object.business_name }}</a>
                                  <br>
                                  <i class="material-icons star-yellow fs-16" style="">
                                      {% for i in object.rating_average_round %}
                                      star
                                      {% endfor %}
                                      {% for i in object.rating_average_round_inverted %}
                                      star_border
                                      {% endfor %}
                                  </i>
                                  <br>
                                  <!-- <span class="fs-12 text-gray-700">{{ object.category.get_name_display }} <span class="text-purple-500 px-1">&#8226;</span> {{ object.subcategory.name }}</span> -->
                                      {% for object in object.rating_average.ratingsystem %}
                                          testimonial
                                      {% endfor %}
                                  <p class="fw-4 text-gray-800 fs-16 fw-6 pt-2">
                                      {{ object.slogan|truncatewords:8 }}
                                  </p>
                                  <div class="fs-14 mt-3 mb-2">
                                      <span class="text-gray-700 fw-4">
                                          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="w-4 icon-location-pin"><path class="fill-purple-500" d="M5.64 16.36a9 9 0 1 1 12.72 0l-5.65 5.66a1 1 0 0 1-1.42 0l-5.65-5.66zM12 13a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/><path class="fill-purple-500" d="M12 1a9 9 0 0 1 6.36 15.36l-5.65 5.66a1 1 0 0 1-.71.3V13a3 3 0 0 0 0-6V1z"/></svg>
                                          {{ object.distance.mi|dividebyth }} Miles Away
                                      </span>
                                  </div>
                                  <!-- url 'portal:merchant_detail' object.state object.city object.offer.first.merchant.category object.offer.first.merchant.subcategory object.offer.first.merchant.business_name object.offer.first.merchant.ref_code -->
                              </div>
                          </div>
                      </div>
                  </div>
              {% endfor %}
              </div>
          </div>
        </div>
    </div>
</section>


{% endblock content %}