mysite/files/urls.py
from django.views.generic.base import TemplateView
from files.views import FilePolicyAPI, FileUploadCompleteHandler, VideoFileUploadView
from django.urls import path


urlpatterns = [

    path('upload/', TemplateView.as_view(template_name='files/upload.html'), name='upload-home'),
    path('api/files/policy/', FilePolicyAPI.as_view(), name='upload-policy'),
    path('api/files/complete/', FileUploadCompleteHandler.as_view(), name='upload-complete'),

    # path('video-upload/store/<slug:slug>/', VideoFileUploadView.as_view(), name='merchant_video_upload'),







]

mysite/portal/urls.py
from django.urls import path

from portal import views as portal_views

app_name = 'portal'

urlpatterns = [

    path('category/<slug:slug>/', portal_views.CategoryDetailView.as_view(), name='category_detail'),
    # path('category/all/', portal_views.CategoryListView.as_view(), name='category_list'),
    path('category/<category>/<slug:slug>', portal_views.SubcategoryDetailView.as_view(), name='subcategory_detail'),

    #Consumer Views
    path('stores/', portal_views.ConsumerStoreListView.as_view(), name='consumer_store_list'),
    path('store/<slug:slug>/', portal_views.ConsumerStoreDetailView.as_view(), name='consumer_store_detail'),

    #Connections
    path('store-connect/', portal_views.StoreChangeConnectionsAjax.as_view(), name='store_change_connections'),
    path('offer-connect/', portal_views.StoreOfferAjax.as_view(), name='offer_change_connections')

]

mysite/users/urls.py
from django.conf.urls import url
from django.urls import path
from users import views as users_views
from users import views_approval as users_approval_views
from users import views_admin as users_admin_views
from portal import views as portal_views
from files import views as files_views

urlpatterns = [

    path('dashboard/', users_views.userPage.as_view(), name='userPage'),
    path('admin/dashboard', users_admin_views.AdminDashboardView.as_view(), name='admin_dashboard'),

    # Admin Dashboard
    path('admin/approve-users', users_admin_views.AdminApproveUsersView.as_view(), name='admin_approve_users'),
    path('admin/manage-subscriptions', users_admin_views.AdminManageSubscriptionsView.as_view(), name='admin_manage_subscriptions'),

    #Consumer User Profile
    path('dashboard/location/', users_views.userLocaton.as_view(), name='user_location'),
    path('dashboard/rewards/', users_views.userRewards.as_view(), name='user_rewards'),
    path('dashboard/favorite-offers/', users_views.userFavorites.as_view(), name='user_favorites'),
    path('dashboard/merchant-offers/', users_views.userFavorites.as_view(), name='user_merchants'),
    url(r'^users/~redirect/$', users_views.UserRedirectView.as_view(), name='redirect'),
    url(r'^users/~update/$', users_views.UserUpdateView.as_view(), name='user_profile_update'),
    url(r'^users/redirectprofile/$', users_views.RedirectProfileView.as_view(), name='redirectprofile'),

    #Merchant
    # path('my-subscription/', users_views.MerchantSubscriptionsView.as_view(), name='subscription_list'),

    # Merchant Store Views
    path('my-store/<slug:slug>/', portal_views.MerchantStoreDetailView.as_view(), name='merchant_store_detail'),
    path('my-stores/', portal_views.MerchantStoreListView.as_view(), name='merchant_store_list'),
    # path('my-store/create/', portal_views.MerchantStoreCreateView.as_view(), name='merchant_store_create'), #REMOVED
    path('my-store/<slug:slug>/update/', portal_views.MerchantStoreUpdateView.as_view(), name='merchant_store_update'),
    path('my-store/<slug:slug>/delete/', portal_views.MerchantStoreDeleteView.as_view(), name='merchant_store_delete'),


    #Merchant Offer Views
    path('my-offers/', portal_views.MerchantOfferListView.as_view(), name='merchant_offer_list'),
    path('my-offers/create/', portal_views.MerchantOfferCreateView.as_view(), name='merchant_offer_create'),
    path('my-offer/<slug:slug>/', portal_views.MerchantOfferDetailView.as_view(), name='merchant_offer_detail'),
    path('my-offer/<slug:slug>/update/', portal_views.MerchantOfferUpdateView.as_view(), name='merchant_offer_update'),
    path('my-offer/<slug:slug>/delete/', portal_views.MerchantOfferDeleteView.as_view(), name='merchant_offer_delete'),
    path('my-offer/like/', portal_views.OfferLike, name='offer_like'),

    #Merchant Signup Forms
    path('merchant-signup/', users_views.MerchantSignUpView.as_view(), name='merchant-signup'),

    #Merchant Approval Views
    path('approval/store/create/', users_approval_views.MerchantApprovalStoreCreateView.as_view(), name='merchant_approval_store_create'),
    path('approval/store/create/additional/',  users_approval_views.MerchantApprovalAdditionalStoreView.as_view(), name='merchant_approval_additional_store'),
    path('approval/store/upload/content/<slug:slug>/', files_views.MerchantContentDetailView.as_view(), name='merchant_content_detait'),
    path('approval/store/upload/file-type/<slug:slug>/', files_views.FileUploadSelector.as_view(), name='merchant_approval_file_select'),
    path('approval/store/upload/image/<slug:slug>/', files_views.ImageFileUploadView.as_view(), name='merchant_approval_image_upload'),
    path('approval/store/upload/video/<slug:slug>/', files_views.VideoFileUploadView.as_view(), name='merchant_approval_video_upload'),
    path('approval/store/upload/file/<slug:slug>/', files_views.FileUploadView.as_view(), name='merchant_approval_file_upload'),

    #Video
    path('my-video/<slug:slug>/delete', files_views.MerchantVideoFileDeleteView.as_view(), name='merchant_video_delete'),
    path('my-video/<slug:slug>/', files_views.MerchantVideoFileDetailView.as_view(), name='merchant_video_detail'),

    #Images
    path('my-images/<slug:slug>/delete', files_views.MerchantImageFileDeleteView.as_view(), name='merchant_image_delete'),
    path('my-images/<slug:slug>/', files_views.MerchantImageFileDetailView.as_view(), name='merchant_image_detail'),

    #Downloadable Content
    path('my-files/<slug:slug>/delete', files_views.MerchantFileDeleteView.as_view(), name='merchant_file_delete'),
    path('my-files/<slug:slug>/', files_views.MerchantFileDetailView.as_view(), name='merchant_file_detail'),

    #Merchant Testimonials
    path('my-reviews/', portal_views.MerchantTestimonialListView.as_view(), name='merchant_testimonial_list'),
    path('new-review/<slug:slug>/', portal_views.MerchantTestimonialCreateView.as_view(), name='merchant_testimonial_create'),

    #Connections
    path('connect/<str:operator>/<int:pk>', users_views.ChangeConnections, name='change_connections'),


]

mysite/portal/views.py
# <**************************************************************************>
# <*****                         IMPORTS                                *****>
# <**************************************************************************>
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from django.utils.text import slugify
from django.conf import settings
## DEBUG:
#messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages

from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.mixins import LoginRequiredMixin
from portal import models as portal_models
from django.views.generic import ListView, DetailView, View, CreateView, DeleteView, UpdateView
# Create your views here.

from django.contrib.gis.db import models
from django.contrib.gis.geos import Point
from django.contrib.gis.db.models.functions import Distance

from location.functions import set_location_cookies, get_ip, get_or_set_location
from users.decorators import user_is_merchant
from .forms import MerchantStoreForm, MerchantTestimonialForm
from users.decorators import IsMerchantMixin, IsUserObject

import stripe

from users import models as users_models
from payments import models as payments_models

STRIPE_PUB_KEY = settings.STRIPE_PUB_KEY
STRIPE_SECRET_KEY = settings.STRIPE_SECRET_KEY

def get_user_orders(request, user):
	user_orders_qs = portal_models.Order.objects.filter(user=user)
	if user_orders_qs.exists():
		return user_orders_qs
	return None


# <**************************************************************************>
# <*****                        CONSUMER VIEWS                          *****>
# <**************************************************************************>

# class CategoryListView(ListView):
# 	model = portal_models.Category


class CategoryDetailView(ListView):
	model = portal_models.Store
	template_name = 'portal/category_detail.html'
	paginate_by = 24

	def get_queryset(self, **kwargs):
		city_state = get_or_set_location(self.request)
		user_location = city_state["user_location"]
		slug = self.kwargs['slug']
		#Query Stores Nearby
		try:
			category_qs = portal_models.Category.objects.get(slug=slug)
			object_list = self.model.objects.annotate(distance = Distance("location", user_location)).order_by("distance").filter(status=2, category=category_qs)
			return object_list
		except ObjectDoesNotExist:
			return redirect('home-page')


	def get_context_data(self, **kwargs):
		context = super(CategoryDetailView, self).get_context_data(**kwargs)
		context['category_list'] = portal_models.Category.objects.all()
		city_state = get_or_set_location(self.request)
		context['city'] = city_state["city"]
		context['state'] = city_state["state"]
		context['category'] = slug = self.kwargs['slug']
		return context


class SubcategoryDetailView(ListView):
	model = portal_models.Store
	template_name = 'portal/subcategory_detail.html'
	paginate_by = 24

	def get_queryset(self, **kwargs):
		city_state = get_or_set_location(self.request)
		user_location = city_state["user_location"]
		slug = self.kwargs['slug']
		#Query Stores Nearby
		subcategory_qs = portal_models.Subcategory.objects.get(slug=slug)
		object_list = self.model.objects.annotate(distance = Distance("location", user_location)).order_by("distance").filter(status=2, subcategory=subcategory_qs)
		return object_list

	def get_context_data(self, **kwargs):
		context = super(SubcategoryDetailView, self).get_context_data(**kwargs)
		context['category_list'] = portal_models.Category.objects.all()
		city_state = get_or_set_location(self.request)
		context['city'] = city_state["city"]
		context['state'] = city_state["state"]
		context['subcategory'] = slug = self.kwargs['slug']
		return context

class ConsumerStoreListView(ListView): #This needs to filter by user city or distance
	model = portal_models.Store
	template_name = 'portal/category_detail.html'
	paginate_by = 3

	def get_queryset(self):
		city_state = get_or_set_location(self.request)
		user_location = city_state["user_location"]
		#Query Stores Nearby
		object_list = self.model.objects.annotate(distance = Distance("location", user_location)).order_by("distance").filter(status=2)
		print(object_list)
		return object_list


	def get_context_data(self, **kwargs):
		context = super(ConsumerStoreListView, self).get_context_data(**kwargs)
		context['category_list'] = portal_models.Category.objects.all()
		city_state = get_or_set_location(self.request)
		context['city'] = city_state["city"]
		context['state'] = city_state["state"]

		#Check to see if follows exist
		try:
			store_connection = portal_models.FollowStore.objects.get(current_user = self.request.user)
			context['store_connections'] = store_connection.connections.all()
		except:
			pass

		return context


class ConsumerStoreDetailView(DetailView): #This needs to filter by user city or distance
	model = portal_models.Store
	template_name = 'portal/consumer/consumer_store_detail.html'

	def get_context_data(self, **kwargs):
		context = super(ConsumerStoreDetailView, self).get_context_data(**kwargs)

		image_list_first_carousel_qs = self.object.imagefile.all()[:4]
		context['image_list_first_carousel'] = image_list_first_carousel_qs

		try:
			image_list_second_carousel_qs = self.object.imagefile.all()[4:8]
			context['image_list_second_carousel'] = image_list_second_carousel_qs
		except:
			pass



		try:
			if self.request.user.is_authenticated:
				store_connection_qs = portal_models.FollowStore.objects.filter(current_user=self.request.user)
				if store_connection_qs.exists():
					store_connection = portal_models.FollowStore.objects.get(current_user= self.request.user)
					context['store_connection_user'] = store_connection.connections.all()

				context['authenticated'] = True
			else:
				context['authenticated'] = False
		except:
			context['authenticated'] = False

		# context['related_stores'] = portal_models.Store.objects.filter(category=self.object.category, active=True).exclude(business_name=self.object.business_name)
		return context

	def get_object(self):
		obj = super(ConsumerStoreDetailView, self).get_object()
		obj.views += 1
		obj.save()
		return obj


# <**************************************************************************>
# <*****                      Visible by Merchants only                 *****>
# <**************************************************************************>

# Merchant Store

class MerchantStoreDetailView(LoginRequiredMixin, IsMerchantMixin, DetailView):
	model = portal_models.Store
	template_name = 'portal/merchant/merchant_detail_mpm.html'
	context_object_name = 'store'

	def get_context_data(self, **kwargs):

		context = super(MerchantStoreDetailView, self).get_context_data(**kwargs)
		store_pk = self.object.pk

		image_list_first_carousel_qs = self.object.imagefile.all()[:4]
		context['image_list_first_carousel'] = image_list_first_carousel_qs

		try:
			image_list_second_carousel_qs = self.object.imagefile.all()[4:8]
			context['image_list_second_carousel'] = image_list_second_carousel_qs
		except:
			pass


		store_offer_qs = portal_models.StoreOffer.objects.filter(current_store=store_pk)
		if store_offer_qs.exists():
			store_offer = store_offer_qs.first()
			context['added_offers'] = store_offer.offers.all()

		context['offers'] = portal_models.Offer.objects.filter(author=self.request.user)
		return context

class MerchantStoreListView(LoginRequiredMixin, IsMerchantMixin, ListView):
	model = portal_models.Store
	template_name = 'portal/merchant/merchant_store_list.html'

	def get_queryset(self):
		store_list = portal_models.Store.objects.filter(merchant=self.request.user)
		return store_list

	def get_context_data(self, **kwargs):
		context = super(MerchantStoreListView, self).get_context_data(**kwargs)
		subscription_qs = payments_models.Subscription.objects.filter(user=self.request.user)

		if subscription_qs.exists():
			subscription = subscription_qs.first()
			context['subscription'] = subscription

		return context





class MerchantStoreUpdateView(LoginRequiredMixin, IsMerchantMixin, SuccessMessageMixin,  UpdateView):
	model = portal_models.Store
	form_class = MerchantStoreForm
	template_name = 'portal/merchant/merchant_store_update.html'
	success_message = "Store Updated"
	success_url = reverse_lazy('users:merchant_store_list')

	def form_valid(self, form):
		form.instance.status = 3
		return super(MerchantStoreUpdateView, self).form_valid(form)


class MerchantStoreDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
	model = portal_models.Store
	template_name = 'portal/merchant/merchant_store_delete.html'
	# success_url = reverse_lazy('users:merchant_store_list')
	success_message = "Store Deleted"

	def get_context_data(self, **kwargs):
		context = super(MerchantStoreDeleteView, self).get_context_data(**kwargs)
		subscription_qs = payments_models.Subscription.objects.filter(user=self.request.user)
		if subscription_qs:
			context['subscription'] = subscription_qs.first()
		return context

	def delete(self, request, *args, **kwargs):
		self.object = self.get_object()
		self.object.delete()

		stripe.api_key	= STRIPE_SECRET_KEY
		subscription_qs	= payments_models.Subscription.objects.filter(user=self.request.user)

		if subscription_qs.exists():
			subscription 		= subscription_qs.first()
			subscription_id 	= subscription.subscription_id

			if subscription.subscription_status == 'active':

				if self.request.user.merchant_profile.stores < subscription.subscription_quantity and self.request.user.merchant_profile.stores > 0:
					messages.success(self.request, 'Your store was deleted succesfully!')
					return redirect('payments:subscription_manage', slug=subscription.slug)

				elif self.request.user.merchant_profile.stores == 0:

					subscription = stripe.Subscription.delete(

mysite/templates/portal/store/func_store_list_view.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-12">
            <h3>Store List</h3>
        </div>
        <div class="col-12">
            <h3>Search for content here:</h3>
            <input type="text">
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-12">
            {% for store in stores %}
            <div class="card faq-card">
                <div class="card-body">
                    <div class="card-title">
                        <a class="card-link" href="{{ store.get_absolute_url }}">
                            <h3>{{ store.business_name }}</h3>
                        </a>
                    </div>
                    <p class="card-text">{{ store.description }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %} 

mysite/templates/portal/store/merchant_approval_nav.html
{% load static %}

{% block merchant_approval_nav %}
<div class="col-lg-8 offset-lg-2 offset-md-0 offset-sm-0 mb-4">
    <div class="tab-pane show active" id="component-1-1" role="tabpanel" aria-labelledby="component-1-1">
      <div class="component-example">
        <div class="container">
          <div class="row">
            <div class="col">
              <div class="owl-carousel visible" data-items="[3,2]" data-margin="20">

                <a href="{% url 'merchant_profile_update' pk=user.merchant_profile.pk %}">
                    <div class="step {% if '/approval/profile/' in request.path %} fw-6 text-primary fw-6 {% endif %}">
                      <h4 class="step-title {% if '/approval/profile/' in request.path %} fw-6 text-primary {% else %} text-secondary {% endif %}">Basic Information</h4>
                    </div>
                </a>
                <div class="step {% if request.path == '/approval/store/create/' %} fw-6 text-primary fw-6 {% endif %} ">
                  <h4 class="step-title {% if request.path == '/approval/store/create/' %} fw-6 text-primary {% else %} text-secondary {% endif %}">Create a Store</h4>
                </div>
                <div class="step">
                  <h4 class="step-title {% if request.path == 'payment' %} fw-6 text-primary {% else %} text-secondary {% endif %}">Subscription</h4>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock merchant_approval_nav %}

mysite/templates/portal/store/merchant_offer_store_detail.html
{% extends 'base-alt.html' %}

{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-8">
            <h3>{{ object.business_name }}</h3>
            <p>{{ object.created_at|date:'F d, Y' }}</p>
            <h3>{{ object.description }}</h3>
            <h3>{{ object.merchant }}</h3>
        </div>
        <div class="col-4">
        {% if object.offers.count %}
            {% for offer in object.offers.all %}
                <h3>{{ offer.title }}</h3>
                <p>{{ offer.description }}</p>
                <form action="{% url 'portal:offer_remove' store.id offer.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Remove</button>
                </form>
            {% endfor %}
        {% else %}
            <h3>No Offers</h3>
        {% endif %}
        <hr>
        {% if offers.count %}
            {% for offer in offers.all %}
                {{ offer.title }}
                <form action="{% url 'portal:offer_add' store.id offer.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Add</button>
                </form>
            {% endfor %}
        {% else %}
                <h3>{{ object.business_name }} Has All Offers</h3>
        {% endif %}
        </div>
    </div>
</div>
{% endblock content %} 

mysite/templates/portal/store/merchant_store_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-12">
            <h3>Store List</h3>
        </div>
        <!-- <div class="col-12">
            <h3>Search for content here:</h3>
            <input type="text">
        </div> -->
    </div>
    <div class="row mt-5">
        <div class="col-12">
            {% for store in object_list %}
            <div class="card faq-card">
                <div class="card-body">
                    <div class="card-title">
                        <a class="card-link" href="{{ store.get_absolute_url }}">
                            <h3>{{ store.business_name }}</h3>
                        </a>
                    </div>
                    <p class="card-text">{{ store.description }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %} 

mysite/templates/portal/store/store_create.html
{% extends 'base.html' %}

{% block content %}
<div class="section">
    <div class="container">
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary" type="submit">Create</button>
        </form>
    </div>
</div>
{% endblock content %} 

mysite/templates/portal/store/store_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="section">
    <div class="container">
        <div class="row mt-5">
            <div class="col-12">
                <h3>Delete Store - {{ object.business_name }}</h3>
                <h3>{{ object.merchant }} Are you sure you want to delete this Store?</h3>
                <form action="" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-danger" type="submit">Delete</button>
                    <a class="btn btn-warning" href="{% url 'portal:merchant_store_detail' object.slug %}">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %} 

mysite/templates/portal/store/store_update.html
{% extends 'base.html' %}

{% block content %}
<div class="section">
    <div class="container">
        <div class="row mt-5">
            <div class="col-8">
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-success" type="submit">Update</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %} 