mysite/files/urls.py
from django.views.generic.base import TemplateView
from files.views import FilePolicyAPI, FileUploadCompleteHandler, VideoFileUploadView
from django.urls import path


urlpatterns = [

    path('upload/', TemplateView.as_view(template_name='files/upload.html'), name='upload-home'),
    path('api/files/policy/', FilePolicyAPI.as_view(), name='upload-policy'),
    path('api/files/complete/', FileUploadCompleteHandler.as_view(), name='upload-complete'),

    # path('video-upload/store/<slug:slug>/', VideoFileUploadView.as_view(), name='merchant_video_upload'),







]

mysite/portal/urls.py
from django.urls import path

from portal import views as portal_views

app_name = 'portal'

urlpatterns = [

    path('category/<slug:slug>/', portal_views.CategoryDetailView.as_view(), name='category_detail'),
    # path('category/all/', portal_views.CategoryListView.as_view(), name='category_list'),
    path('category/<category>/<slug:slug>', portal_views.SubcategoryDetailView.as_view(), name='subcategory_detail'),

    #Consumer Views
    path('stores/', portal_views.ConsumerStoreListView.as_view(), name='consumer_store_list'),
    path('store/<slug:slug>/', portal_views.ConsumerStoreDetailView.as_view(), name='consumer_store_detail'),

    #Connections
    path('store-connect/', portal_views.StoreChangeConnectionsAjax.as_view(), name='store_change_connections'),
    path('offer-connect/', portal_views.StoreOfferAjax.as_view(), name='offer_change_connections')

]

mysite/portal/forms.py
from django import forms
import datetime
from phonenumber_field.formfields import PhoneNumberField
from django.contrib.admin.widgets import AdminDateWidget
from django.forms.widgets import SelectDateWidget
from django.forms.fields import DateField
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _
from portal import models as portal_models

from portal.fields import GroupedModelChoiceField

# Customize Crispy forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, HTML, Field, Div
from django.utils.safestring import mark_safe
from crispy_forms.bootstrap import (
    PrependedText, PrependedAppendedText, FormActions, StrictButton)




class MerchantStoreForm(forms.ModelForm):
    subcategory = GroupedModelChoiceField(queryset=portal_models.Subcategory.objects.all(), choices_groupby='category')

    class Meta:
       model = portal_models.Store
       fields = [
       'business_name',
       'slogan',
       'description',
       # 'category',
       'subcategory',
       'street_address',
       'city',
       'state',
       'zip',
       'phone_number',
       'code_coupon',
       'website_url',
       'facebook_url',
       'logo',
       'id',
       ]


    def __init__(self, *args, **kwargs):
        super(MerchantStoreForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        #self.helper.form_id = 'id-exampleForm'
        #elf.helper.form_class = 'blueForms'
        self.helper.form_action = 'Submit'
        self.helper.layout = Layout(
            #Div('first_name', style="background: white;", title="Explication title", css_class="bigdivs")
            Field(
                Div(
                    HTML("<h3 class='subheader text-uppercase text-gray-700 fs-16 mb-2'>Basic Info<h3>"),
                    HTML("<p class='text-secondary fs-14'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.<p>"),
                css_class="col-lg-6"
                ),
                Div(
                'business_name',
                # 'category',
                'subcategory',
                css_class="col-lg-6 pb-4"
                ),
                Div(
                    HTML("<hr>"),
                css_class="col-lg-12"
                ),
                Div(
                    HTML("<h3 class='subheader text-uppercase text-gray-700 fs-16 mb-2'>Address<h3>"),
                    HTML("<p class='text-secondary fs-14'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.<p>"),
                css_class="col-lg-6"
                ),
                Div(
                'street_address',
                'city',
                'state',
                'zip',
                'phone_number',
                css_class="col-lg-6"
                ),
                Div(
                    HTML("<hr>"),
                css_class="col-lg-12"
                ),
                Div(
                    HTML("<h3 class='subheader text-uppercase text-gray-700 fs-16 mb-2'>Marketing<h3>"),
                    HTML("<p class='text-secondary fs-14'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.<p>"),
                css_class="col-lg-6"
                ),
                Div(
                'code_coupon',
                'slogan',
                'description',
                'website_url',
                'facebook_url',
                    Div(
                    'logo',
                    css_class="custom-input-button"
                    ),
                css_class="col-lg-6"
                ),

                Div(
                    HTML("<hr>"),
                css_class="col-lg-12"
                ),
                # Div(
                #     Submit('Save', 'Create Store', css_class='btn btn-primary-alt btn-block mt-3 pull-right'),
                # css_class="col-lg-12"
                # ),
            ),
    )



class MerchantTestimonialForm(forms.ModelForm):
    class Meta:
       model = portal_models.Testimonial
       fields = [

       'title',
       'review',
       'rating',
       ]


    def __init__(self, *args, **kwargs):
        super(MerchantTestimonialForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        #self.helper.form_id = 'id-exampleForm'
        #elf.helper.form_class = 'blueForms'
        self.helper.form_action = 'Submit'
        self.helper.layout = Layout(
            Field(
                Div(
                'title',
                'review',
                'rating',
                css_class="col-lg-12 pb-4"
                ),
            ),
    )

mysite/portal/views.py
# <**************************************************************************>
# <*****                         IMPORTS                                *****>
# <**************************************************************************>
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from django.utils.text import slugify
from django.conf import settings
## DEBUG:
#messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages

from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.mixins import LoginRequiredMixin
from portal import models as portal_models
from django.views.generic import ListView, DetailView, View, CreateView, DeleteView, UpdateView
# Create your views here.

from django.contrib.gis.db import models
from django.contrib.gis.geos import Point
from django.contrib.gis.db.models.functions import Distance

from location.functions import set_location_cookies, get_ip, get_or_set_location
from users.decorators import user_is_merchant
from .forms import MerchantStoreForm, MerchantTestimonialForm
from users.decorators import IsMerchantMixin, IsUserObject

import stripe

from users import models as users_models
from payments import models as payments_models

STRIPE_PUB_KEY = settings.STRIPE_PUB_KEY
STRIPE_SECRET_KEY = settings.STRIPE_SECRET_KEY

def get_user_orders(request, user):
	user_orders_qs = portal_models.Order.objects.filter(user=user)
	if user_orders_qs.exists():
		return user_orders_qs
	return None


# <**************************************************************************>
# <*****                        CONSUMER VIEWS                          *****>
# <**************************************************************************>

# class CategoryListView(ListView):
# 	model = portal_models.Category


class CategoryDetailView(ListView):
	model = portal_models.Store
	template_name = 'portal/category_detail.html'
	paginate_by = 24

	def get_queryset(self, **kwargs):
		city_state = get_or_set_location(self.request)
		user_location = city_state["user_location"]
		slug = self.kwargs['slug']
		#Query Stores Nearby
		try:
			category_qs = portal_models.Category.objects.get(slug=slug)
			object_list = self.model.objects.annotate(distance = Distance("location", user_location)).order_by("distance").filter(status=2, category=category_qs)
			return object_list
		except ObjectDoesNotExist:
			return redirect('home-page')


	def get_context_data(self, **kwargs):
		context = super(CategoryDetailView, self).get_context_data(**kwargs)
		context['category_list'] = portal_models.Category.objects.all()
		city_state = get_or_set_location(self.request)
		context['city'] = city_state["city"]
		context['state'] = city_state["state"]
		context['category'] = slug = self.kwargs['slug']
		return context


class SubcategoryDetailView(ListView):
	model = portal_models.Store
	template_name = 'portal/subcategory_detail.html'
	paginate_by = 24

	def get_queryset(self, **kwargs):
		city_state = get_or_set_location(self.request)
		user_location = city_state["user_location"]
		slug = self.kwargs['slug']
		#Query Stores Nearby
		subcategory_qs = portal_models.Subcategory.objects.get(slug=slug)
		object_list = self.model.objects.annotate(distance = Distance("location", user_location)).order_by("distance").filter(status=2, subcategory=subcategory_qs)
		return object_list

	def get_context_data(self, **kwargs):
		context = super(SubcategoryDetailView, self).get_context_data(**kwargs)
		context['category_list'] = portal_models.Category.objects.all()
		city_state = get_or_set_location(self.request)
		context['city'] = city_state["city"]
		context['state'] = city_state["state"]
		context['subcategory'] = slug = self.kwargs['slug']
		return context

class ConsumerStoreListView(ListView): #This needs to filter by user city or distance
	model = portal_models.Store
	template_name = 'portal/category_detail.html'
	paginate_by = 3

	def get_queryset(self):
		city_state = get_or_set_location(self.request)
		user_location = city_state["user_location"]
		#Query Stores Nearby
		object_list = self.model.objects.annotate(distance = Distance("location", user_location)).order_by("distance").filter(status=2)
		print(object_list)
		return object_list


	def get_context_data(self, **kwargs):
		context = super(ConsumerStoreListView, self).get_context_data(**kwargs)
		context['category_list'] = portal_models.Category.objects.all()
		city_state = get_or_set_location(self.request)
		context['city'] = city_state["city"]
		context['state'] = city_state["state"]

		#Check to see if follows exist
		try:
			store_connection = portal_models.FollowStore.objects.get(current_user = self.request.user)
			context['store_connections'] = store_connection.connections.all()
		except:
			pass

		return context


class ConsumerStoreDetailView(DetailView): #This needs to filter by user city or distance
	model = portal_models.Store
	template_name = 'portal/consumer/consumer_store_detail.html'

	def get_context_data(self, **kwargs):
		context = super(ConsumerStoreDetailView, self).get_context_data(**kwargs)

		image_list_first_carousel_qs = self.object.imagefile.all()[:4]
		context['image_list_first_carousel'] = image_list_first_carousel_qs

		try:
			image_list_second_carousel_qs = self.object.imagefile.all()[4:8]
			context['image_list_second_carousel'] = image_list_second_carousel_qs
		except:
			pass



		try:
			if self.request.user.is_authenticated:
				store_connection_qs = portal_models.FollowStore.objects.filter(current_user=self.request.user)
				if store_connection_qs.exists():
					store_connection = portal_models.FollowStore.objects.get(current_user= self.request.user)
					context['store_connection_user'] = store_connection.connections.all()

				context['authenticated'] = True
			else:
				context['authenticated'] = False
		except:
			context['authenticated'] = False

		# context['related_stores'] = portal_models.Store.objects.filter(category=self.object.category, active=True).exclude(business_name=self.object.business_name)
		return context

	def get_object(self):
		obj = super(ConsumerStoreDetailView, self).get_object()
		obj.views += 1
		obj.save()
		return obj


# <**************************************************************************>
# <*****                      Visible by Merchants only                 *****>
# <**************************************************************************>

# Merchant Store

class MerchantStoreDetailView(LoginRequiredMixin, IsMerchantMixin, DetailView):
	model = portal_models.Store
	template_name = 'portal/merchant/merchant_detail_mpm.html'
	context_object_name = 'store'

	def get_context_data(self, **kwargs):

		context = super(MerchantStoreDetailView, self).get_context_data(**kwargs)
		store_pk = self.object.pk

		image_list_first_carousel_qs = self.object.imagefile.all()[:4]
		context['image_list_first_carousel'] = image_list_first_carousel_qs

		try:
			image_list_second_carousel_qs = self.object.imagefile.all()[4:8]
			context['image_list_second_carousel'] = image_list_second_carousel_qs
		except:
			pass


		store_offer_qs = portal_models.StoreOffer.objects.filter(current_store=store_pk)
		if store_offer_qs.exists():
			store_offer = store_offer_qs.first()
			context['added_offers'] = store_offer.offers.all()

		context['offers'] = portal_models.Offer.objects.filter(author=self.request.user)
		return context

class MerchantStoreListView(LoginRequiredMixin, IsMerchantMixin, ListView):
	model = portal_models.Store
	template_name = 'portal/merchant/merchant_store_list.html'

	def get_queryset(self):
		store_list = portal_models.Store.objects.filter(merchant=self.request.user)
		return store_list

	def get_context_data(self, **kwargs):
		context = super(MerchantStoreListView, self).get_context_data(**kwargs)
		subscription_qs = payments_models.Subscription.objects.filter(user=self.request.user)

		if subscription_qs.exists():
			subscription = subscription_qs.first()
			context['subscription'] = subscription

		return context





class MerchantStoreUpdateView(LoginRequiredMixin, IsMerchantMixin, SuccessMessageMixin,  UpdateView):
	model = portal_models.Store
	form_class = MerchantStoreForm
	template_name = 'portal/merchant/merchant_store_update.html'
	success_message = "Store Updated"
	success_url = reverse_lazy('users:merchant_store_list')

	def form_valid(self, form):
		form.instance.status = 3
		return super(MerchantStoreUpdateView, self).form_valid(form)


class MerchantStoreDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
	model = portal_models.Store
	template_name = 'portal/merchant/merchant_store_delete.html'
	# success_url = reverse_lazy('users:merchant_store_list')
	success_message = "Store Deleted"

	def get_context_data(self, **kwargs):
		context = super(MerchantStoreDeleteView, self).get_context_data(**kwargs)
		subscription_qs = payments_models.Subscription.objects.filter(user=self.request.user)
		if subscription_qs:
			context['subscription'] = subscription_qs.first()
		return context

	def delete(self, request, *args, **kwargs):
		self.object = self.get_object()
		self.object.delete()

		stripe.api_key	= STRIPE_SECRET_KEY
		subscription_qs	= payments_models.Subscription.objects.filter(user=self.request.user)

		if subscription_qs.exists():
			subscription 		= subscription_qs.first()
			subscription_id 	= subscription.subscription_id

			if subscription.subscription_status == 'active':

				if self.request.user.merchant_profile.stores < subscription.subscription_quantity and self.request.user.merchant_profile.stores > 0:
					messages.success(self.request, 'Your store was deleted succesfully!')
					return redirect('payments:subscription_manage', slug=subscription.slug)

				elif self.request.user.merchant_profile.stores == 0:

					subscription = stripe.Subscription.delete(

mysite/templates/portal/consumer/consumer_store_list.html
{% extends "base.html" %}
{% load location_extra %}
{% load static %}


{% block content %}

{% block category_nav %}
  {% include "portal/category_nav.html" %}
{% endblock category_nav %}

<section class="section container">
    <h2 class="header text-dark">Trending Services Located Near {{ city }}, {{ state }}</h2>
    <br>
    <div class="row">

        {% for object in object_list %}
        <div class="col-lg-3 col-md-6 col-sm-6 text-center border-radius-300 mb-5 px-m-na-3" >
            <div class="card shadow-5">
                <a class="" href="{{ object.get_consumer_absolute_url }}">
                    <img class="img-fluid border-radius-100" style="max-height: 250px;" src="{{ AwsBucketMediaURL }}{{ object.logo }}" alt="User Uploaded images">
                </a>
                <div class="card-body py-1">
                    <div class=" text-left mt-3">
                        <h3 class="fw-6 text-dark fs-18 mb-1">{{ object.business_name }}</h3>
                            {% if object.rating_average == 1 %}
                            <i class="material-icons star-yellow fs-18">star star_border star_border star_border star_border </i>{% endif %}
                            {% if object.rating_average == 2 %}
                            <i class="material-icons star-yellow fs-18"> star star star_border star_border star_border </i>{% endif %}
                            {% if object.rating_average == 3 %}
                            <i class="material-icons star-yellow fs-18"> star star star star_border star_border </i>{% endif %}
                            {% if object.rating_average == 4 %}
                            <i class="material-icons star-yellow fs-18"> star star star star star_border </i>{% endif %}
                            {% if object.rating_average == 5 %}
                            <i class="material-icons star-yellow fs-18"> star star star star star </i>{% endif %}
                        <h4 class="fw-4 text-gray-700 fs-14 pt-2">
                            {{ object.slogan|truncatewords:8 }}
                        </h4>
                        <div class="fs-14 mt-3 mb-2">
                            <span class="text-gray-700 fw-4">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="w-4 icon-location-pin"><path class="fill-gray-500" d="M5.64 16.36a9 9 0 1 1 12.72 0l-5.65 5.66a1 1 0 0 1-1.42 0l-5.65-5.66zM12 13a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/><path class="fill-purple-500" d="M12 1a9 9 0 0 1 6.36 15.36l-5.65 5.66a1 1 0 0 1-.71.3V13a3 3 0 0 0 0-6V1z"/></svg>
                                {{ object.distance.mi|dividebyth }} Miles Away
                            </span>
                            <a href="#TODO" class="btn btn-primary">Follow</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% if is_paginated %}
    <div class="py-3 text-center">
    <nav aria-label="Page navigation example">
      <ul class="pagination pull-right">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
            {% endif %}
      </ul>
    </nav>
    </div>
    {% endif %}
</section>
</div>
{% endblock content %}

{% block jquery %}
  $(".followBtn").click(function (event) {
    event.preventDefault();

    var this_ = $(this);
    var storepk = this_.attr('data-catid');
    var action_type = this_.attr('action_type');

    $.ajax({
      type: "POST",
      url: "{% url 'portal:store_change_connections' %}",
      data: {
        store_pk: storepk,
        action: action_type,
        csrfmiddlewaretoken: '{{ csrf_token }}',
      },
      success: function (data) {

        document.location.reload(true)
        console.log(data)

      }
    });
    return false;
  });
{% endblock jquery %}