mysite/files/urls.py
from django.views.generic.base import TemplateView
from files.views import FilePolicyAPI, FileUploadCompleteHandler, VideoFileUploadView
from django.urls import path


urlpatterns = [

    path('upload/', TemplateView.as_view(template_name='files/upload.html'), name='upload-home'),
    path('api/files/policy/', FilePolicyAPI.as_view(), name='upload-policy'),
    path('api/files/complete/', FileUploadCompleteHandler.as_view(), name='upload-complete'),

    # path('video-upload/store/<slug:slug>/', VideoFileUploadView.as_view(), name='merchant_video_upload'),







]

mysite/mysite/urls.py
from django.conf import settings

from django.conf.urls import include, url
from django.urls import path
from django.contrib import admin
from .views import (
    homeView,
    AltHomeView,
)
from .views import set_location_cookies
from search import views as search_views
#sitemaps
from django.contrib.sitemaps.views import sitemap
from django.contrib.flatpages.sitemaps import FlatPageSitemap
#Rerouting django admin through allauth
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from allauth.account import views as allauthviews

#Stemletic App Models
from .views import security

admin.site.login = staff_member_required(login_url='/', redirect_field_name='')(admin.site.login)

from .sitemaps import StaticSitemap, SupportSitemap, QuestionSitemap, TopicSitemap, StoreSitemap, CategorySitemap, SubcategorySitemap

sitemaps = {
    'mysite': StaticSitemap,
    'support': SupportSitemap,
    'question': QuestionSitemap,
    'topic': TopicSitemap,
    'store': StoreSitemap,
    'category': CategorySitemap,
    'subcategory': SubcategorySitemap
}

urlpatterns = [

    #Admin
    path('admin/', admin.site.urls),
    #SiteMap
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    #path('alt-home/', AltHomeView.as_view(), name='alt-home'),
    path('', homeView.as_view(), name='home-page'),
    #Security
    path('.well-known/security.txt', security, name='security'),
    #Authentication
    url(r'^accounts/', include('allauth.urls')),
    #Portal
    url(r'^shop/', include(('portal.urls', 'portal'), namespace='portal')),
    #Location
    url(r'^', include(('location.urls', 'location'), namespace='location')),
    #Portal
    path('payments/', include(('payments.urls', 'payments'), namespace='payments')),
    #FAQ
    url(r'^support/', include(('support.urls', 'support'), namespace='support')),
    #users
    url(r'', include(('users.urls', 'users'), namespace='users')),
    #files
    url(r'^', include(('files.urls', 'files'), namespace='files')),
    #FlatPages
    path('pages', include('django.contrib.flatpages.urls')),
    #Search
    #path('search', search_views.search, name='search'),
    url(r'^search/autocomplete/$', search_views.autocomplete),
    url(r'^find/', search_views.FacetedSearchView.as_view(), name='haystack_search'),
    #Ckeditor
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),


    path('sitemap.xml', sitemap,
        {'sitemaps': {'flatpages': FlatPageSitemap}},
        name='django.contrib.sitemaps.views.sitemap'),


    #Development
    # path('components/', components, name='components-page'),
]

if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

mysite/payments/urls.py
from django.urls import path

from payments import views as payments_views
from payments import views_webhooks as payments_views_webhooks

urlpatterns = [
    path('plans/', payments_views.PlanListView.as_view(), name='plan_list'),
    path('plan/<slug:slug>/', payments_views.PlanDetailView.as_view(), name='plan_detail'),

    path('subscription/<slug:slug>', payments_views.SubscriptionDetailView.as_view(), name='subscription_detail'),
    path('subscription/<slug:slug>/manage', payments_views.SubscriptionManageView.as_view(), name='subscription_manage'),

    path('manage-payment-method', payments_views.PaymentMethodManageView.as_view(), name='payment_method_manage'),

    path('webhook/', payments_views_webhooks.TrialWebhook.as_view(), name='webhook'),

    path('charge/', payments_views.Charge.as_view(), name='charge'),

    path('apply-promo', payments_views.ApplyPromo, name='apply_promo')
]

mysite/users/urls.py
from django.conf.urls import url
from django.urls import path
from users import views as users_views
from users import views_approval as users_approval_views
from users import views_admin as users_admin_views
from portal import views as portal_views
from files import views as files_views

urlpatterns = [

    path('dashboard/', users_views.userPage.as_view(), name='userPage'),
    path('admin/dashboard', users_admin_views.AdminDashboardView.as_view(), name='admin_dashboard'),

    # Admin Dashboard
    path('admin/approve-users', users_admin_views.AdminApproveUsersView.as_view(), name='admin_approve_users'),
    path('admin/manage-subscriptions', users_admin_views.AdminManageSubscriptionsView.as_view(), name='admin_manage_subscriptions'),

    #Consumer User Profile
    path('dashboard/location/', users_views.userLocaton.as_view(), name='user_location'),
    path('dashboard/rewards/', users_views.userRewards.as_view(), name='user_rewards'),
    path('dashboard/favorite-offers/', users_views.userFavorites.as_view(), name='user_favorites'),
    path('dashboard/merchant-offers/', users_views.userFavorites.as_view(), name='user_merchants'),
    url(r'^users/~redirect/$', users_views.UserRedirectView.as_view(), name='redirect'),
    url(r'^users/~update/$', users_views.UserUpdateView.as_view(), name='user_profile_update'),
    url(r'^users/redirectprofile/$', users_views.RedirectProfileView.as_view(), name='redirectprofile'),

    #Merchant
    # path('my-subscription/', users_views.MerchantSubscriptionsView.as_view(), name='subscription_list'),

    # Merchant Store Views
    path('my-store/<slug:slug>/', portal_views.MerchantStoreDetailView.as_view(), name='merchant_store_detail'),
    path('my-stores/', portal_views.MerchantStoreListView.as_view(), name='merchant_store_list'),
    # path('my-store/create/', portal_views.MerchantStoreCreateView.as_view(), name='merchant_store_create'), #REMOVED
    path('my-store/<slug:slug>/update/', portal_views.MerchantStoreUpdateView.as_view(), name='merchant_store_update'),
    path('my-store/<slug:slug>/delete/', portal_views.MerchantStoreDeleteView.as_view(), name='merchant_store_delete'),


    #Merchant Offer Views
    path('my-offers/', portal_views.MerchantOfferListView.as_view(), name='merchant_offer_list'),
    path('my-offers/create/', portal_views.MerchantOfferCreateView.as_view(), name='merchant_offer_create'),
    path('my-offer/<slug:slug>/', portal_views.MerchantOfferDetailView.as_view(), name='merchant_offer_detail'),
    path('my-offer/<slug:slug>/update/', portal_views.MerchantOfferUpdateView.as_view(), name='merchant_offer_update'),
    path('my-offer/<slug:slug>/delete/', portal_views.MerchantOfferDeleteView.as_view(), name='merchant_offer_delete'),
    path('my-offer/like/', portal_views.OfferLike, name='offer_like'),

    #Merchant Signup Forms
    path('merchant-signup/', users_views.MerchantSignUpView.as_view(), name='merchant-signup'),

    #Merchant Approval Views
    path('approval/store/create/', users_approval_views.MerchantApprovalStoreCreateView.as_view(), name='merchant_approval_store_create'),
    path('approval/store/create/additional/',  users_approval_views.MerchantApprovalAdditionalStoreView.as_view(), name='merchant_approval_additional_store'),
    path('approval/store/upload/content/<slug:slug>/', files_views.MerchantContentDetailView.as_view(), name='merchant_content_detait'),
    path('approval/store/upload/file-type/<slug:slug>/', files_views.FileUploadSelector.as_view(), name='merchant_approval_file_select'),
    path('approval/store/upload/image/<slug:slug>/', files_views.ImageFileUploadView.as_view(), name='merchant_approval_image_upload'),
    path('approval/store/upload/video/<slug:slug>/', files_views.VideoFileUploadView.as_view(), name='merchant_approval_video_upload'),
    path('approval/store/upload/file/<slug:slug>/', files_views.FileUploadView.as_view(), name='merchant_approval_file_upload'),

    #Video
    path('my-video/<slug:slug>/delete', files_views.MerchantVideoFileDeleteView.as_view(), name='merchant_video_delete'),
    path('my-video/<slug:slug>/', files_views.MerchantVideoFileDetailView.as_view(), name='merchant_video_detail'),

    #Images
    path('my-images/<slug:slug>/delete', files_views.MerchantImageFileDeleteView.as_view(), name='merchant_image_delete'),
    path('my-images/<slug:slug>/', files_views.MerchantImageFileDetailView.as_view(), name='merchant_image_detail'),

    #Downloadable Content
    path('my-files/<slug:slug>/delete', files_views.MerchantFileDeleteView.as_view(), name='merchant_file_delete'),
    path('my-files/<slug:slug>/', files_views.MerchantFileDetailView.as_view(), name='merchant_file_detail'),

    #Merchant Testimonials
    path('my-reviews/', portal_views.MerchantTestimonialListView.as_view(), name='merchant_testimonial_list'),
    path('new-review/<slug:slug>/', portal_views.MerchantTestimonialCreateView.as_view(), name='merchant_testimonial_create'),

    #Connections
    path('connect/<str:operator>/<int:pk>', users_views.ChangeConnections, name='change_connections'),


]

mysite/users/forms.py
from django import forms
from .models import Profile

from allauth.account.forms import SignupForm
from django import forms
from users import models as users_models
from users import views as users_views

from portal import models as portal_models

# Customize Crispy forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, HTML, Field, Div
from django.utils.safestring import mark_safe
from crispy_forms.bootstrap import (
    PrependedText, PrependedAppendedText, FormActions, StrictButton)

RETURN_CHOICES = (
    ('F', 'Found a better deal'),
    ('S', 'Not satisfied with the quality'),
    ('T', 'Took too long to arrive'),
    ('N', 'None of the above')
)

class userLocationForm(forms.Form):
    city_input = forms.CharField(label="City, State", initial='Explore coupons in what city?',required=True, widget=forms.TextInput(attrs={
        'style': 'display: none;',
    }))

    state_input = forms.CharField(label="City, State", initial='Explore coupons in what city?',required=True, widget=forms.TextInput(attrs={
        'style': 'display: none;',
    }))


class MerchantSignupForm(SignupForm):
    first_name = forms.CharField(max_length=30, label='First Name')
    last_name = forms.CharField(max_length=30, label='Last Name')

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.helper = FormHelper(self)
    #     self.helper.layout = Layout(
    #         Row(
    #             Column('first_name', css_class='form-group col-md-6 mb-0'),
    #             Column('last_name', css_class='form-group col-md-6 mb-0'),
    #             css_class='form-row'
    #         ),
    #         Submit('submit', 'Sign in')
    #     )

    def save(self, request):
        user = super(MerchantSignupForm, self).save(request)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.is_merchant = True
        user.is_active = True
        user.save()
        return user


# class ConsumerSignupForm(SignupForm):
#     def save(self, request):
#         user = super(ConsumerSignupForm, self).save(request)
#         user.is_consumer = True
#         user.is_active = True
#         user.save()
#         return user





# <**************************************************************************>
# <*****                      Merchant Approval Forms                   *****>
# <**************************************************************************>
#
# class MerchantProfileForm(forms.ModelForm):
#     class Meta:
#        model = users_models.MerchantProfile
#        fields = [
#         'business_name',
#            'street_address',
#            'city',
#            'state',
#            'zip',
#            'phone_number',
#            'website_url',
#            'facebook_url',
#        ]
#
#     def __init__(self, *args, **kwargs):
#         super(MerchantProfileForm, self).__init__(*args, **kwargs)
#
#         self.helper = FormHelper()
#         #self.helper.form_id = 'id-exampleForm'
#         #elf.helper.form_class = 'blueForms'
#         self.helper.form_action = 'Submit'
#         self.helper.layout = Layout(
#             #Div('first_name', style="background: white;", title="Explication title", css_class="bigdivs")
#             Field(
#                 Div(
#                 'business_name',
#                 css_class="col-lg-12 pb-4"
#                 ),
#                 Div(
#                 'street_address',
#                 css_class="col-lg-6 pb-4"
#                 ),
#                 Div(
#                 'city',
#                 css_class="col-lg-6 pb-4"
#                 ),
#                 Div(
#                 'state',
#                 css_class="col-lg-6 pb-4"
#                 ),
#                 Div(
#                 'zip',
#                 css_class="col-lg-6 pb-4"
#                 ),
#                 Div(
#                 'phone_number',
#                 css_class="col-lg-6 pb-4"
#                 ),
#
#         ),
#     )

mysite/templates/users/approval/merchant_approval_additional_store.html
{% extends 'base.html' %}

{% block content %}
<div class="section-sm">
    <div class="container">
        <div class="row my-5">
            <div class="col-lg-6 offset-3">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <h1 class="fs-24 fw-6 mb-3">Store Creation Successful!</h1>
                                {% if subscription %}
                                    {% if subscription.subscription_status == 'active' %}
                                        <p class="text-secondary fs-14">
                                            Please upgrade your subscription to begin the approval process for your recently created store(s).
                                        </p>
                                        <p class="fs-18 fw-4 mb-1">Next Steps:</p>
                                        <p class="fs-14 fw-4 ml-2 mb-2">
                                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="w-8 mr-4 icon-certificate"><path class="primary" d="M4 3h16a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5c0-1.1.9-2 2-2zm16 12V7a2 2 0 0 1-2-2H6a2 2 0 0 1-2 2v8a2 2 0 0 1 2 2h12c0-1.1.9-2 2-2zM8 7h8a1 1 0 0 1 0 2H8a1 1 0 1 1 0-2z"></path><path class="secondary" d="M11.65 18.23a4 4 0 1 1 4.7 0l2.5 3.44-2.23-.18-1.48 1.68-.59-4.2a4.04 4.04 0 0 1-1.1 0l-.6 4.2-1.47-1.68-2.23.18 2.5-3.44zM14 17a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"></path></svg>
                                            <span>
                                                Upgrade Subscription
                                            </span>
                                        </p>
                                        <p class="fs-14 fw-4 ml-2 mb-2">
                                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="w-8 mr-4 icon-store"><path class="primary" d="M5 8h14a1 1 0 0 1 1 1v11a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V9a1 1 0 0 1 1-1zm1 2v7h12v-7H6z"></path><path class="secondary" d="M6 12a4 4 0 0 1-4-4 1 1 0 0 1 .1-.45l2-4A1 1 0 0 1 5 3h14a1 1 0 0 1 .9.55l2 4c.06.14.1.3.1.45a4 4 0 0 1-7 2.65 3.99 3.99 0 0 1-6 0A3.99 3.99 0 0 1 6 12z"></path></svg>
                                            <span>
                                                Create another store
                                            </span>
                                        </p>
                                        <p class="fs-14 fw-4 ml-2">
                                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="w-8 mr-4 icon-edit"><path class="fill-orange-500" d="M4 14a1 1 0 0 1 .3-.7l11-11a1 1 0 0 1 1.4 0l3 3a1 1 0 0 1 0 1.4l-11 11a1 1 0 0 1-.7.3H5a1 1 0 0 1-1-1v-3z"/><rect width="20" height="2" x="2" y="20" class="fill-orange-500" rx="1"/></svg>
                                            <span>
                                                Manage exisitng stores <a href="{% url 'users:merchant_store_list' %}">here</a>
                                            </span>
                                        </p>
                                    {% else %}
                                        <p class="text-secondary fs-14">
                                            It looks like you have purchased a subscription in the past, but your status is <span class="text-danger">{{ subscription.subscription_status }}</span>. Please repurchase a subscription to begin the approval process for your recently created store(s).
                                        </p>
                                        <p class="fs-18 fw-4 mb-1">Next Steps:</p>
                                        <p class="fs-14 fw-4 ml-2 mb-2">
                                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="w-8 mr-4 icon-certificate"><path class="primary" d="M4 3h16a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5c0-1.1.9-2 2-2zm16 12V7a2 2 0 0 1-2-2H6a2 2 0 0 1-2 2v8a2 2 0 0 1 2 2h12c0-1.1.9-2 2-2zM8 7h8a1 1 0 0 1 0 2H8a1 1 0 1 1 0-2z"></path><path class="secondary" d="M11.65 18.23a4 4 0 1 1 4.7 0l2.5 3.44-2.23-.18-1.48 1.68-.59-4.2a4.04 4.04 0 0 1-1.1 0l-.6 4.2-1.47-1.68-2.23.18 2.5-3.44zM14 17a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"></path></svg>
                                            <span>
                                                Purchase a Subscription
                                            </span>
                                        </p>
                                        <p class="fs-14 fw-4 ml-2 mb-2">
                                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="w-8 mr-4 icon-store"><path class="primary" d="M5 8h14a1 1 0 0 1 1 1v11a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V9a1 1 0 0 1 1-1zm1 2v7h12v-7H6z"></path><path class="secondary" d="M6 12a4 4 0 0 1-4-4 1 1 0 0 1 .1-.45l2-4A1 1 0 0 1 5 3h14a1 1 0 0 1 .9.55l2 4c.06.14.1.3.1.45a4 4 0 0 1-7 2.65 3.99 3.99 0 0 1-6 0A3.99 3.99 0 0 1 6 12z"></path></svg>
                                            <span>
                                                Create another store
                                            </span>
                                        </p>
                                    {% endif %}
                                {% else %}
                                    <p class="text-secondary fs-14">
                                        Please purchase a subscription to begin the approval process for your recently created store(s).
                                    </p>
                                    <p class="fs-18 fw-4 mb-1">Next Steps:</p>
                                    <p class="fs-14 fw-4 ml-2 mb-2">
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="w-8 mr-4 icon-certificate"><path class="primary" d="M4 3h16a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5c0-1.1.9-2 2-2zm16 12V7a2 2 0 0 1-2-2H6a2 2 0 0 1-2 2v8a2 2 0 0 1 2 2h12c0-1.1.9-2 2-2zM8 7h8a1 1 0 0 1 0 2H8a1 1 0 1 1 0-2z"></path><path class="secondary" d="M11.65 18.23a4 4 0 1 1 4.7 0l2.5 3.44-2.23-.18-1.48 1.68-.59-4.2a4.04 4.04 0 0 1-1.1 0l-.6 4.2-1.47-1.68-2.23.18 2.5-3.44zM14 17a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"></path></svg>
                                        <span>
                                            Purchase a Subscription
                                        </span>
                                    </p>
                                    <p class="fs-14 fw-4 ml-2 mb-2">
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="w-8 mr-4 icon-store"><path class="primary" d="M5 8h14a1 1 0 0 1 1 1v11a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V9a1 1 0 0 1 1-1zm1 2v7h12v-7H6z"></path><path class="secondary" d="M6 12a4 4 0 0 1-4-4 1 1 0 0 1 .1-.45l2-4A1 1 0 0 1 5 3h14a1 1 0 0 1 .9.55l2 4c.06.14.1.3.1.45a4 4 0 0 1-7 2.65 3.99 3.99 0 0 1-6 0A3.99 3.99 0 0 1 6 12z"></path></svg>
                                        <span>
                                            Create another store
                                        </span>
                                    </p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="card-footer mt-2">
                        <div class="text-right">
                            <a href="{% url 'users:merchant_approval_store_create' %}" class="btn btn-secondary-inverted mr-2" >Create Additional Store</a>
                            {% if subscription.subscription_status == 'active' %}
                                <a href="{% url 'payments:subscription_manage' slug=subscription.slug %}" class="btn btn-primary-alt mr-2">Upgrade Subscription</a>
                            {% else %}
                                <a href="{% url 'payments:plan_list' %}" class="btn btn-primary-alt mr-2">No, Let me Checkout</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="py-5 hide"></div>
        <div class="py-5 hide"></div>
    </div>
</div>
{% endblock content %}

mysite/templates/users/approval/merchant_approval_nav.html
{% load static %}

{% block merchant_approval_nav %}
<div class="col-lg-8 offset-lg-2 offset-md-0 offset-sm-0 mb-4">
    <br /><br />
    <ul class="list-unstyled multi-steps">
      <li>Sign Up</li>
      <li class="{% if request.path == '/approval/store/create/' %} is-active {% endif %}"><a href="{% url 'users:merchant_approval_store_create'%}">Create Store</a></li>
      <li class="{% if '/payments/plan/' in request.path %} is-active {% else %} {% endif %}">Payment</li>
      <li class="{% if request.path == '/approval/store/media-upload/' %} is-active {% else %} {% endif %}">Video Upload</li>
    </ul>
</div>
{% endblock merchant_approval_nav %}

mysite/templates/users/approval/merchant_approval_video_list.html
{% extends 'base.html' %}

{% block content %}
<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="border-success-md px-5 py-4">
                  <h2 class="text-success fw-7"><i class="fa fa-check fs-28" aria-hidden="true"></i>Thank you, you are now an Offical Gegoo Member!</h2>
                  An email confirmation has been sent to you. Now for the last step, upload a video for each store below.
                  <br>
                </div>
            </div>

            {% block merchant_approval_nav %}
              {% include "users/approval/merchant_approval_nav.html" %}
            {% endblock merchant_approval_nav %}
            <div class="col-lg-12 mt-4">
                <div class="card shadow-2">
                    <div class="card-body">
                        <h3 class="header">
                            Video Upload
                            <a href="/dashboard/" class="btn btn-primary-inverted pull-right mt-2">Skip Video Upload</a>
                            <br>


                        </h3>
                        <p class="text-secondary fs-14 fw-4">
                            Upload a 15 second video that promotes the products and services of your business. <br>Each store is a seperate upload, but all stores can have the same video.
                        </p>
                    </div>
                </div>
            </div>

                {% for store in store_list %}

                <div class="col-lg-6 my-2">

                    {% if store.video_file %}

                    <div class="card shadow-2 mt-4">
                        <div class="card-body p-3">
                            <video  style="display: block; margin: auto;" width="100%" controls controlsList="nodownload" webkitallowfullscreen mozallowfullscreen allowfullscreen poster="{{ store.banner }}">
                				<source src="https://static-gegoo-bucket.s3.amazonaws.com/media/{{ store.video_file.file }}" type="video/mp4"> Sorry, your browser doesn't support embedded videos.
            				</video>
                        </div>
                        <div class="card-footer">
                            <div class="row">
                                <div class="col-lg-6 vertical-container">
                                    <div class="vertical-alignment">
                                        <h4 class="text-secondary fs-14">
                                            Uploaded {{ store.video_file.uploaded_at }}
                                        </h4>
                                    </div>
                                </div>
                                <div class="col-lg-6 text-right">
                                    <a href="{% url 'users:merchant_video_delete' store.video_file.slug %}" class=" mr-2">Delete Video</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% else %}

                    <div class="card shadow-2 mt-3">
                        <div class="card-body">
                            <div class="pb-2">
                                <h3 class="card-title fs-16 fw-6 text-uppercase">{{ store.business_name }} <span class="pull-right fs-14 fw-4 text-muted">{{ store.city }}, {{ store.state }}</span></h3>
                            </div>
                            <a href="{% url 'users:merchant_approval_video_upload' slug=store.slug %}">
                            <div class="bg-gray-100 vertical-container" style="height:300px;">
                                <div class="vertical-alignment text-center">
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="w-12  icon-videocam"><path class="fill-gray-400" d="M13.59 12l6.7-6.7A1 1 0 0 1 22 6v12a1 1 0 0 1-1.7.7L13.58 12z"/><rect width="14" height="14" x="2" y="5" class="fill-gray-400" rx="2"/></svg>
                                    <h4 class="subheader text-purple-500">Upload a Video for your Stores</h4>
                                    <p class="text-secondary fs-14">Grab visitors attention with a short 15 second <br>video that showcases your business.</p>
                                </div>
                            </div>
                            </a>

                        </div>
                    </div>

                    {% endif %}

                </div>
                {% endfor %}

                <div class="col-lg-12">

                        <a href="/dashboard/" class="btn btn-primary-alt btn-block my-5">Finish</a>

                </div>


        </div>
    </div>
</section>
{% endblock content %}